services:
  # 백엔드 서비스
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: sss-backend-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bta_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./BE:/app
      - gradle-cache:/root/.gradle
    depends_on:
      - db
    networks:
      - sss-network
    restart: unless-stopped

  # 프론트엔드 서비스
  frontend:
    image: node:22.12.0
    container_name: sss-frontend-dev
    ports:
      - "3000:5173"
    volumes:
      - ./FE:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - sss-network
    restart: unless-stopped

  # 데이터베이스 서비스
  db:
    image: postgres:16-alpine
    container_name: sss-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bta_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - sss-network
    restart: unless-stopped

networks:
  sss-network:
    driver: bridge

volumes:
  postgres-data-dev:
  gradle-cache: 