services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: sss-frontend
    profiles:
      - builder 
    networks:
      - sss-network

  nginx:
    image: nginx:latest
    container_name: sss-nginx
    ports:
      - "80:80"  # HTTP 포트
      - "443:443"  # HTTPS 포트
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./FE/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro   # ← 🔐 인증서 읽기 전용 마운트
    depends_on:
      - backend
    networks:
      - sss-network
    restart: unless-stopped

  backend:
    image: sss-backend:latest
    container_name: sss-backend
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      - API_PASSWORD=${API_PASSWORD}
    depends_on:
      - db
      - mongo
    networks:
      - sss-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: sss-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sss-network
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: sss-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - sss-network
    restart: unless-stopped

networks:
  sss-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
