services:
  # 백엔드 서비스
  backend:
    image: sss-backend:latest
    container_name: sss-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sss_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/sss_db
    depends_on:
      - db
      - mongo
    networks:
      - sss-network
    restart: unless-stopped

  # 프론트엔드 서비스
  frontend:
    image: sss-frontend:latest
    container_name: sss-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sss-network
    restart: unless-stopped

  # PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:16-alpine
    container_name: sss-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sss_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sss-network
    restart: unless-stopped

  # MongoDB 데이터베이스 서비스
  mongo:
    image: mongo:7.0
    container_name: sss-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sss_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-mongodb}
    volumes:
      - mongo-data:/data/db
    networks:
      - sss-network
    restart: unless-stopped

networks:
  sss-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data: 