FROM node:22.12.0

# 시스템 의존성 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

# 기본 포트 노출
EXPOSE 5173 