version: "3.8"

services:
  ai-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ZONOS_DEFAULT_MODEL=Zyphra/Zonos-v0.1-transformer
    command: python FastAPI/main.py --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
