services:
  app:
    build: .
    container_name: ai-iamge-service-gpu
    ports:
      - "8001:8001"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
